--[[ ----------------------------------------------------------------------------------------------- 
 File       : dialogs_labx5.script
 Description: Диалоговые функции для Лаборатории x5
 Copyright  : 2011 © Spectrum Project
 Author		: Geonezis
 Last edit  : 30.03.2014 (by БолотныйДоктор)
--]] -----------------------------------------------------------------------------------------------
--/											
--]] -----------------------------------------------------------------------------------------------


function labx5_alf_quest(first_speaker, second_speaker)	
   task_manager.get_task_manager():give_task("labx5_quest_doc")  
end
